"""H2 as registered, plus the context-engineering arms (2026-09-21).

H2 (Project_Plan_2, Sec. II-C): *LLM-generated temporal user profiles will
achieve higher NDCG@10 than interaction-derived embeddings for users in the
lowest quartile of interaction counts.* The paper reports H2 as registered but
not tested, because no profile it evaluated was generated by a language model.

REGISTERED FAMILY (modal_run.py::h2, batch 512, three ablation seeds):
  LLM        CAFREC + the generated profile cache, `plain` prompt
  Template   CAFREC + the templated behavioural profile (bge, d1024)
  Stand-in   CAFREC with the trainable per-user embedding  <- H2's "interaction-
             derived embedding", so LLM vs Stand-in is the registered test
  CAFREC-NP  no long-term branch at all, as a second reading

PRIMARY TEST, pre-stated here before any result is read:
  LLM vs Stand-in, NDCG@10, lowest activity quartile (<= 12 organic clicks).
  H2 is supported if that difference is positive and survives Holm within the
  four-test registered family. Everything else is secondary.

EXPLORATORY ARMS, reported separately and never inside the registered family,
because each changes what the profile is:
  LLM-KAR      knowledge-inference prompt, same inputs (Xi et al., RecSys 2024)
  LLM-Collab   + items from the nearest long-history users (Wu et al., KDD 2024)
  LLM-Support  + those users' category mixes as in-context examples
  HistGate     template profile + the RON-45 history gate, re-run at batch 512
               (its Cycle-10 result predates the tiers.py batch fix)
Holm is applied within the exploratory set separately, and the two families are
never pooled. Arms with no result files on disk are skipped, so this can be run
after each arm finishes rather than only at the end.

Statistics are `analyze_plan_hypotheses.compare`: per-user metric averaged over
seeds, two-sided Wilcoxon signed-rank (normal approximation), paired bootstrap
95% CI over 2,000 user resamples, and per-seed significance / sign counts.
Cohorts are `analyze_plan_hypotheses.cohorts`, unchanged.

Usage (from cafrec_harness/, after pulling the result JSONs into results/modal/):
    .venv/Scripts/python analyze_h2.py
    .venv/Scripts/python analyze_h2.py --seeds 2020,2021,403092
Writes results/h2_<date>.txt and .json.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import time

import numpy as np

from analyze_plan_hypotheses import BOOT_SEED, compare, cohorts, holm

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results", "modal")
H2_DIR = os.path.join(HERE, "..", "data", "h2")
PROFILE_DIR = os.path.join(HERE, "..", "data", "profiles")
DATE = time.strftime("%Y-%m-%d")

LLM, TEMPLATE, STANDIN, NOPROF = "LLM", "Template", "Stand-in", "CAFREC-NP"
KAR, COLLAB, SUPPORT, HISTGATE = "LLM-KAR", "LLM-Collab", "LLM-Support", "HistGate"
RANK0, RANK6, RANK64 = "Rank-0", "Rank-6", "Rank-64"
RANK128, RANK256, RAND256, HASHING = "Rank-128", "Rank-256", "Rand-256", "Hashing"
REGISTERED = (LLM, TEMPLATE, STANDIN, NOPROF)
EXPLORATORY = (KAR, COLLAB, SUPPORT, HISTGATE)
# Rank sweep: the same LLM text and encoder, PCA-truncated to varying rank, rows
# renormalised. Rank-0 gives every user the corpus mean, i.e. zero per-user
# information. Rand-32 keeps the rank and each user's scores but randomises the
# principal directions. Hashing is the no-content frozen profile, re-run here on
# today's code path so its point in the rank/accuracy table is like-for-like.
RANK_ARMS = (RANK0, RANK6, RANK64, RANK128, RANK256, RAND256, HASHING)
RANK_CACHE = {RANK0: "llm_rank0", RANK6: "llm_rank6", RANK64: "llm_rank64",
              RANK128: "llm_rank128", RANK256: "llm_rank256",
              RAND256: "llm_rand256", HASHING: "hashing"}
# prompt variant behind each LLM arm, for the coverage check and the sidecars
VARIANT_OF = {LLM: "plain", KAR: "kar", COLLAB: "collab", SUPPORT: "support"}

# h2_* tags come from modal_run.py::h2. The fallbacks are the pre-existing
# ablation-seed runs, so `--conditions llm_plain` alone (3 jobs instead of 12)
# still analyses; the file listing below shows which pairing was actually used.
PATS = {
    LLM:      ["CAFREC_kuairand_pure_ctx_h2_llm_plain_s{s}_seed{s}_*.json"],
    KAR:      ["CAFREC_kuairand_pure_ctx_h2_llm_kar_s{s}_seed{s}_*.json"],
    COLLAB:   ["CAFREC_kuairand_pure_ctx_h2_llm_collab_s{s}_seed{s}_*.json"],
    SUPPORT:  ["CAFREC_kuairand_pure_ctx_h2_llm_support_s{s}_seed{s}_*.json"],
    HISTGATE: ["CAFREC_kuairand_pure_ctx_h2_histgate_s{s}_seed{s}_*.json"],
    TEMPLATE: ["CAFREC_kuairand_pure_ctx_h2_template_s{s}_seed{s}_*.json",
               "CAFREC_kuairand_pure_ctx_bge_topk_s{s}_seed{s}_*.json"],
    STANDIN:  ["CAFREC_kuairand_pure_ctx_h2_standin_s{s}_seed{s}_*.json",
               "CAFREC_kuairand_pure_ctx_standin_s{s}_seed{s}_*.json",
               "CAFREC_kuairand_pure_ctx_standin_seed{s}_*.json"],
    NOPROF:   ["CAFREC_kuairand_pure_ctx_h2_noprof_s{s}_seed{s}_*.json",
               "CAFREC_kuairand_pure_ctx_noprof_topk_s{s}_seed{s}_*.json"],
    RANK0:    ["CAFREC_kuairand_pure_ctx_h2_llm_rank0_s{s}_seed{s}_*.json"],
    RANK6:    ["CAFREC_kuairand_pure_ctx_h2_llm_rank6_s{s}_seed{s}_*.json"],
    RANK64:   ["CAFREC_kuairand_pure_ctx_h2_llm_rank64_s{s}_seed{s}_*.json"],
    RANK128:  ["CAFREC_kuairand_pure_ctx_h2_llm_rank128_s{s}_seed{s}_*.json"],
    RANK256:  ["CAFREC_kuairand_pure_ctx_h2_llm_rank256_s{s}_seed{s}_*.json"],
    RAND256:  ["CAFREC_kuairand_pure_ctx_h2_llm_rand256_s{s}_seed{s}_*.json"],
    HASHING:  ["CAFREC_kuairand_pure_ctx_h2_hashing_s{s}_seed{s}_*.json",
               "CAFREC_kuairand_pure_ctx_hash_s{s}_seed{s}_*.json"],
}


def _path(name, seed):
    for pat in PATS[name]:
        hits = sorted(glob.glob(os.path.join(RES, pat.format(s=seed))))
        if hits:
            return hits[-1]
    return None


class Runs:
    """Per-user metric matrices [n_seeds, n_users] on one user order."""

    def __init__(self, users):
        self.users = users
        self.index = {u: i for i, u in enumerate(users)}
        self.cache, self.raw = {}, {}

    def load(self, name, seed):
        if (name, seed) not in self.raw:
            path = _path(name, seed)
            if path is None:
                raise FileNotFoundError(
                    f"{name} seed {seed}: no result JSON in {RES}. Run "
                    f"`modal run modal_run.py::h2`, then\n"
                    f"  python -m modal volume get cafrec-results "
                    f"'CAFREC_kuairand_pure_ctx_h2_*' results/modal/")
            with open(path) as fh:
                d = json.load(fh)
            d["_file"] = os.path.basename(path)
            self.raw[(name, seed)] = d
        return self.raw[(name, seed)]

    def get(self, name, seeds):
        key = (name, tuple(seeds))
        if key in self.cache:
            return self.cache[key]
        ranks = np.full((len(seeds), len(self.users)), np.nan)
        for j, s in enumerate(seeds):
            d = self.load(name, s)
            for u, r in zip(d["test_user_ids"], d["test_ranks"]):
                i = self.index.get(str(u))
                if i is not None and r is not None:
                    ranks[j, i] = r
        assert not np.isnan(ranks).any(), f"{name}: users missing from dump"
        ink = ranks <= 10
        m = {"hit@10": ink.astype(float),
             "ndcg@10": np.where(ink, 1.0 / np.log2(ranks + 1.0), 0.0),
             "mrr@10": np.where(ink, 1.0 / ranks, 0.0)}
        self.cache[key] = m
        return m


_EFF_CACHE = {}


def effective_rank(cache):
    """Effective rank of a profile cache: exp(entropy of the covariance spectrum).

    Prefers the sidecar written at build time; falls back to computing it from
    the local `.pt`, so arms whose caches were built elsewhere (hf, hashing,
    llm_plain) still get a value instead of 'n/a'. Same formula either way.
    """
    if cache in _EFF_CACHE:
        return _EFF_CACHE[cache]
    base = os.path.join(PROFILE_DIR, f"kuairand_pure_ctx.profiles.{cache}.d1024")
    eff = None
    if os.path.exists(base + ".json"):
        eff = json.load(open(base + ".json", encoding="utf-8")).get("effective_rank")
    if eff is None and os.path.exists(base + ".pt"):
        import torch
        X = torch.load(base + ".pt", weights_only=False).float()[1:]
        Xc = (X - X.mean(0)).numpy()
        ev = np.clip(np.linalg.eigvalsh(Xc.T @ Xc / max(len(Xc) - 1, 1)), 0, None)
        tot = ev.sum()
        if tot <= 1e-20:
            eff = 1.0
        else:
            p = ev / tot
            eff = round(float(np.exp(-(p * np.log(p + 1e-12)).sum())), 2)
    _EFF_CACHE[cache] = eff
    return eff


def fmt(r):
    s = (f"  {r['a']:<12} vs {r['b']:<12} {r['cohort']:<16} {r['metric']:<8} "
         f"n={r['n_users']:>6,} d={r['delta']:+.5f} ({r['rel_pct']:+.1f}%) "
         f"CI[{r['ci'][0]:+.5f},{r['ci'][1]:+.5f}] p={r['p']:.3g}")
    if "p_holm" in r:
        s += f" holm={r['p_holm']:.3g}"
    s += f" sig {r['sig']}/{r['seeds']} sign {r['sign']}/{r['seeds']}"
    return s


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seeds", default="2020,2021,403092")
    args = ap.parse_args()
    seeds = [int(s) for s in args.seeds.split(",")]
    rng = np.random.default_rng(BOOT_SEED)
    lines, out = [], {"seeds": seeds, "script": "analyze_h2.py", "date": DATE}

    def say(s=""):
        print(s, flush=True)
        lines.append(s)

    probe = Runs([]).load(NOPROF, seeds[0])
    users = sorted(str(u) for u in probe["test_user_ids"])
    runs = Runs(users)
    masks, meta = cohorts(users)
    q1 = masks["Q1 activity"]

    have = []
    for name in REGISTERED + EXPLORATORY + RANK_ARMS:
        ok = all(_path(name, s) is not None for s in seeds)
        if ok:
            have.append(name)
        elif name in REGISTERED:
            raise SystemExit(f"registered arm {name!r} is missing result files for "
                             f"seeds {seeds}; it cannot be skipped")
    exploratory = [n for n in EXPLORATORY if n in have]
    ranks = [n for n in RANK_ARMS if n in have]

    say(f"H2 AS REGISTERED  {time.strftime('%Y-%m-%d %H:%M:%S')}  seeds {seeds}")
    say(f"users {len(users):,}; activity quartile cuts {meta['quartile_cuts']}; "
        f"lowest quartile n={int(q1.sum()):,}")
    say(f"registered arms {list(REGISTERED)}")
    say(f"exploratory arms present {exploratory}"
        + (f"; absent {[n for n in EXPLORATORY if n not in have]}"
           if len(exploratory) < len(EXPLORATORY) else ""))
    say("")
    say("files:")
    for name in list(REGISTERED) + exploratory + ranks:
        for s in seeds:
            d = runs.load(name, s)
            cfg = d.get("config", {})
            prof = os.path.basename(str(cfg.get("llm_profile_path")))
            say(f"  {name:<12} seed {s:<7} {d['_file']:<62} device={d.get('device')} "
                f"batch={cfg.get('train_batch_size')} ablation={cfg.get('ablation')} "
                f"history_gate={cfg.get('history_gate')} profile={prof} "
                f"HR@10={d['test']['hit@10']:.4f}")
            assert cfg.get("train_batch_size") == 512, \
                f"{name} seed {s} is not at batch 512 — do not pair it with the rest"
    out["files"] = {n: [runs.load(n, s)["_file"] for s in seeds]
                    for n in list(REGISTERED) + exploratory + ranks}

    # ------------------------------------------------------------- coverage
    # A profile the lowest-quartile users do not HAVE cannot test H2: cap_beyond
    # gave every one of them a zero vector. Check before reading any result.
    say("\n== LLM profile coverage (share of users with a non-empty profile) ==")
    cov_all = {}
    for name in [n for n in list(REGISTERED) + exploratory if n in VARIANT_OF]:
        p = os.path.join(H2_DIR, f"profiles.{VARIANT_OF[name]}.jsonl")
        if not os.path.exists(p):
            continue
        got = set()
        for ln in open(p, encoding="utf-8"):
            r = json.loads(ln)
            if (r.get("text") or "").strip():
                got.add(str(r["user_id"]))
        nz = np.array([u in got for u in users])
        cov = {k: float(nz[v].mean()) for k, v in masks.items()}
        cov_all[name] = cov
        say(f"  {name:<12} " + "  ".join(f"{k} {100 * v:.1f}%" for k, v in cov.items()))
        if cov["Q1 activity"] < 0.95:
            say(f"    WARNING: only {100 * cov['Q1 activity']:.1f}% of the lowest "
                f"quartile has a profile — that arm is weakened by coverage, not by H2")
    out["profile_coverage"] = cov_all

    for name in [n for n in list(REGISTERED) + exploratory if n in VARIANT_OF]:
        side = os.path.join(PROFILE_DIR,
                            f"kuairand_pure_ctx.profiles.llm_{VARIANT_OF[name]}.d1024.json")
        if os.path.exists(side):
            sc = json.load(open(side, encoding="utf-8"))
            gen = sc.get("generation", {})
            say(f"  {name:<12} cache nonzero={sc.get('nonzero_users')} "
                f"encoder={sc.get('encoder')} generator={gen.get('model')} "
                f"({gen.get('vllm')}) mean profile {sc.get('profile_chars', {}).get('mean')} chars")
            out.setdefault("caches", {})[name] = {
                k: sc.get(k) for k in ("encoder", "nonzero_users", "embedded",
                                       "skipped_short", "profile_chars")}

    sections = []

    def block(title, rows, family=False):
        if family and rows:
            for r, a in zip(rows, holm(np.array([r["p"] for r in rows]))):
                r["p_holm"] = float(a)
        say(f"\n== {title} ==")
        for r in rows:
            say(fmt(r))
        sections.append({"title": title, "family_corrected": bool(family),
                         "rows": [{k: v for k, v in r.items()
                                   if not k.startswith("_")} for r in rows]})
        return rows

    def cmp(a, b, metric, cohort):
        return compare(runs, a, b, seeds, metric, masks[cohort], rng) | {"cohort": cohort}

    # ---------------------------------------------- 1. PRIMARY + registered family
    family = [
        cmp(LLM, STANDIN, "ndcg@10", "Q1 activity"),      # H2 as registered
        cmp(LLM, TEMPLATE, "ndcg@10", "Q1 activity"),     # does the LLM beat the template?
        cmp(LLM, NOPROF, "ndcg@10", "Q1 activity"),       # does any profile beat none?
        cmp(TEMPLATE, STANDIN, "ndcg@10", "Q1 activity"),  # the paper's +10.6% reading
    ]
    block("1. PRIMARY: lowest activity quartile, NDCG@10; Holm over this 4-test "
          "REGISTERED family", family, family=True)
    primary = family[0]
    verdict = ("SUPPORTED" if primary["delta"] > 0 and primary["p_holm"] < 0.05
               else "NOT SUPPORTED")
    say(f"\n  H2 ({LLM} > {STANDIN}, NDCG@10, lowest quartile): {verdict} "
        f"({primary['rel_pct']:+.1f}%, Holm p={primary['p_holm']:.3g}, "
        f"sign {primary['sign']}/{primary['seeds']} seeds)")
    out["primary"] = {k: v for k, v in primary.items() if not k.startswith("_")}
    out["verdict"] = verdict

    # ---------------------------------------------- 2. secondary readings
    block("2. Lowest activity quartile, HR@10 and MRR@10 (secondary, no Holm)",
          [cmp(LLM, b, m, "Q1 activity") for b in (STANDIN, TEMPLATE, NOPROF)
           for m in ("hit@10", "mrr@10")])

    block("3. All users and the other activity quartiles, NDCG@10 (secondary)",
          [cmp(LLM, b, "ndcg@10", c) for b in (STANDIN, TEMPLATE, NOPROF)
           for c in ("all", "Q2 activity", "Q3 activity", "Q4 activity")])

    block("4. Sparse vs dense and session position, NDCG@10 (secondary)",
          [cmp(LLM, b, "ndcg@10", c) for b in (STANDIN, NOPROF)
           for c in ("sparse (<20)", "dense (>=20)", "short session", "longer session")])

    # ---------------------------------------------- 5. exploratory context arms
    if exploratory:
        rows = [cmp(a, b, "ndcg@10", "Q1 activity")
                for a in exploratory for b in (STANDIN, LLM)]
        block("5. EXPLORATORY context-engineering arms, lowest quartile NDCG@10; "
              "Holm within this set ONLY, never pooled with the registered family",
              rows, family=True)
        block("6. Exploratory arms, lowest quartile HR@10 and MRR@10, and all users "
              "(descriptive)",
              [cmp(a, b, m, c) for a in exploratory for b in (STANDIN,)
               for m, c in (("hit@10", "Q1 activity"), ("mrr@10", "Q1 activity"),
                            ("ndcg@10", "all"))])
    else:
        say("\n== 5-6. EXPLORATORY arms: none on disk yet ==")

    # ---------------------------------------------- rank sweep (exploratory)
    if ranks:
        block("7a. EXPLORATORY rank sweep, lowest quartile NDCG@10, each arm vs the "
              "Stand-in; Holm within the rank set ONLY",
              [cmp(a, STANDIN, "ndcg@10", "Q1 activity") for a in ranks], family=True)
        controls = []
        if RANK256 in ranks and RAND256 in ranks:
            controls.append(cmp(RANK256, RAND256, "ndcg@10", "Q1 activity"))
        if RANK0 in ranks:
            controls += [cmp(RANK0, TEMPLATE, "ndcg@10", "Q1 activity"),
                         cmp(RANK0, LLM, "ndcg@10", "Q1 activity"),
                         cmp(RANK0, NOPROF, "ndcg@10", "Q1 activity")]
        if controls:
            block("7b. Rank-sweep controls: do the DIRECTIONS matter (Rank-32 vs "
                  "Rand-32), and is a CONSTANT profile as good as the template?",
                  controls)

        # the curve itself: measured effective rank against lowest-quartile accuracy
        say("\n== 7c. Profile rank vs lowest-quartile accuracy (the curve) ==")
        curve = []
        for name in ranks + [LLM, TEMPLATE]:
            cache = RANK_CACHE.get(name, VARIANT_OF.get(name) and
                                   f"llm_{VARIANT_OF[name]}")
            if name == TEMPLATE:
                cache = "hf"
            eff = effective_rank(cache) if cache else None
            m = runs.get(name, seeds)
            curve.append(dict(arm=name, cache=cache, effective_rank=eff,
                              q1_ndcg=float(m["ndcg@10"][:, q1].mean()),
                              q1_hr=float(m["hit@10"][:, q1].mean()),
                              all_ndcg=float(m["ndcg@10"].mean())))
        curve.sort(key=lambda r: (r["effective_rank"] is None, r["effective_rank"] or 0))
        say(f"  {'arm':<12} {'eff.rank':>9}  {'Q1 NDCG@10':>11}  {'Q1 HR@10':>9}  {'all NDCG':>9}")
        for r in curve:
            er = f"{r['effective_rank']:.2f}" if r["effective_rank"] is not None else "n/a"
            say(f"  {r['arm']:<12} {er:>9}  {r['q1_ndcg']:>11.5f}  "
                f"{r['q1_hr']:>9.5f}  {r['all_ndcg']:>9.5f}")
        out["rank_curve"] = curve
        sections.append({"title": "7c. rank vs lowest-quartile accuracy",
                         "rows": curve})

    # ---------------------------------------------- 7. absolute numbers
    say("\n== 7. Absolute test metrics (mean over seeds) ==")
    abs_rows = {}
    for name in list(REGISTERED) + exploratory + ranks:
        m = runs.get(name, seeds)
        abs_rows[name] = {k: float(m[k][:, q1].mean()) for k in ("hit@10", "ndcg@10", "mrr@10")}
        allu = {k: float(m[k].mean()) for k in ("hit@10", "ndcg@10", "mrr@10")}
        say(f"  {name:<12} Q1: HR {abs_rows[name]['hit@10']:.4f}  "
            f"NDCG {abs_rows[name]['ndcg@10']:.4f}  MRR {abs_rows[name]['mrr@10']:.4f}   |   "
            f"all: HR {allu['hit@10']:.4f}  NDCG {allu['ndcg@10']:.4f}")
        abs_rows[name]["all_users"] = allu
    out["absolute"] = abs_rows

    out["sections"] = sections
    os.makedirs(os.path.join(HERE, "results"), exist_ok=True)
    txt = os.path.join(HERE, "results", f"h2_{DATE}.txt")
    with open(txt, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(HERE, "results", f"h2_{DATE}.json"), "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=2, default=str)
    print(f"\nwrote {txt}")


if __name__ == "__main__":
    main()
