"""Unified runner.

run_experiment(key, dataset) builds a RecBole config from the shared base
config + the model's contract, then runs the standard
create_dataset -> data_preparation -> fit -> evaluate flow. The ONLY thing
that differs between a built-in and your custom model is how the model class
is resolved, and that branch is hidden in here.
"""
import time
from pathlib import Path

import torch

# RecBole 1.2.1 checkpoints pickle full Config/dataset objects, which torch>=2.6
# refuses to load under its new weights_only=True default. The checkpoints are
# generated by this same process (trusted), so restore the old behaviour.
_torch_load = torch.load


def _torch_load_full(*args, **kwargs):
    kwargs.setdefault("weights_only", False)
    return _torch_load(*args, **kwargs)


torch.load = _torch_load_full

from recbole.config import Config
from recbole.data import create_dataset, data_preparation
from recbole.trainer import Trainer
from recbole.utils import get_model, get_trainer, init_seed, init_logger

from cafrec.registry import get_spec

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASE_CONFIG = REPO_ROOT / "configs" / "base.yaml"


def _resolve_model_class(spec, config):
    """Built-in name -> get_model(); custom class -> use directly."""
    if isinstance(spec.model, str):
        return get_model(config["model"])
    return spec.model  # already a class


def _resolve_trainer(spec, config, model):
    """Custom trainer if given; built-ins get their type-specific trainer;
    a bare custom class falls back to the base Trainer (per RecBole's
    customize-models example)."""
    if spec.trainer is not None:
        return spec.trainer(config, model)
    if isinstance(spec.model, str):
        return get_trainer(config["MODEL_TYPE"], config["model"])(config, model)
    return Trainer(config, model)


def run_experiment(key, dataset="ml-100k", config_overrides=None,
                   base_config=DEFAULT_BASE_CONFIG, return_ranks=False,
                   dump_topk=False):
    """Train + evaluate one model. Returns a flat metrics dict (also the thing
    you persist). `key` is the registry key — the single variable to change."""
    spec = get_spec(key)

    # Merge order: model-specific config < training contract < caller overrides.
    config_dict = {}
    config_dict.update(spec.config)
    config_dict.update(spec.contract)
    if config_overrides:
        config_dict.update(config_overrides)

    # A model may declare `context_load_col` (extra atomic-file columns it needs,
    # e.g. CAFREC's six context features). Promote it to RecBole's `load_col`
    # only for a "_ctx" dataset that actually carries those columns; otherwise
    # drop it so plain datasets load their base columns and the model falls back.
    context_load_col = config_dict.pop("context_load_col", None)
    if context_load_col is not None and str(dataset).endswith("_ctx"):
        config_dict.setdefault("load_col", context_load_col)

    config = Config(
        model=spec.model,                       # str OR class — Config takes both
        dataset=dataset,
        config_file_list=[str(base_config)],
        config_dict=config_dict,
    )
    init_seed(config["seed"], config["reproducibility"])
    init_logger(config)

    rb_dataset = create_dataset(config)
    train_data, valid_data, test_data = data_preparation(config, rb_dataset)

    # Split audit: proves the leave-one-out split populated all three sections
    # for this dataset (train = all-but-last-two, valid = 2nd-last, test = last).
    split_sizes = {
        "n_users": rb_dataset.user_num,
        "n_items": rb_dataset.item_num,
        "n_train": len(train_data.dataset),
        "n_valid": len(valid_data.dataset),
        "n_test": len(test_data.dataset),
    }

    model_cls = _resolve_model_class(spec, config)
    model = model_cls(config, train_data.dataset).to(config["device"])

    trainer = _resolve_trainer(spec, config, model)
    best_valid_score, best_valid_result = trainer.fit(
        train_data, valid_data, saved=True, show_progress=False, verbose=False
    )
    test_result = trainer.evaluate(
        test_data, load_best_model=True, show_progress=False
    )

    result = {
        "model": key,
        "dataset": dataset,
        "seed": config["seed"],
        "loss_type": config["loss_type"],
        "n_params": sum(p.numel() for p in model.parameters()),
        "timestamp": time.strftime("%Y%m%d-%H%M%S"),
        "split_sizes": split_sizes,
        "valid_best": dict(best_valid_result),
        "test": dict(test_result),
    }

    # Per-user held-out ranks for paired significance tests. `model` holds the
    # best checkpoint (evaluate loaded it); we re-score the test split mirroring
    # RecBole's full-sort masking. The aggregate is asserted against test_result
    # so the ranks are provably consistent with the reported metrics.
    if return_ranks or dump_topk:
        from cafrec.eval.full_rank import full_sort_ranks, metrics_at_k
        uid_field = rb_dataset.uid_field
        k = config["topk"][0] if isinstance(config["topk"], list) else config["topk"]
        out = full_sort_ranks(
            model, test_data, config["device"], rb_dataset.item_num, uid_field,
            k=k, collect_topk=dump_topk)
        internal_uids, ranks = out[0], out[1]
        # map RecBole-internal user ids -> original tokens so results pair across
        # models/datasets regardless of each dataset's remap.
        uid_token = rb_dataset.field2id_token[uid_field]
        orig_uids = [str(uid_token[i]) for i in internal_uids]
        if return_ranks:
            result["test_user_ids"] = orig_uids
            result["test_ranks"] = ranks.tolist()
            result["ranks_check"] = metrics_at_k(ranks, k=k)
        if dump_topk:
            # top-k RECOMMENDED items as ORIGINAL item tokens, so the offline
            # ILD/Coverage step aligns them to the KuaiRand video_id category
            # matrix with no remap bookkeeping. Keyed by original user id so
            # diversity can also be stratified per cohort (RON-42/43/44).
            iid_field = rb_dataset.iid_field
            item_token = rb_dataset.field2id_token[iid_field]
            topk = out[2]
            result["test_topk_user_ids"] = orig_uids
            result["test_topk_items"] = [[str(item_token[i]) for i in row]
                                         for row in topk]
            result["topk_k"] = int(k)
            # real catalogue size for Coverage (exclude RecBole's pad item 0)
            result["n_items_catalog"] = int(rb_dataset.item_num - 1)
    return result
